defaults:
  - _self_
  # 任务配置已在本文件内联，无需再从外部引入

task:
  name: mimicgen_abs

  shape_meta: &shape_meta
    obs:
      agentview_image:
        shape: [3, 84, 84]
        type: rgb
      robot0_eye_in_hand_image:
        shape: [3, 84, 84]
        type: rgb
      robot0_eef_pos:
        shape: [3]
      robot0_eef_quat:
        shape: [4]
      robot0_gripper_qpos:
        shape: [2]
    action:
      shape: [10]

  abs_action: &abs_action True

  env_runner:
    _target_: diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner
    dataset_path: ${dataset_path}
    shape_meta: *shape_meta
    n_train: 6
    n_train_vis: 2
    train_start_idx: 0
    n_test: 50
    n_test_vis: 4
    test_start_seed: 100000
    max_steps: ${get_max_steps:${task_name}}
    n_obs_steps: ${n_obs_steps}
    n_action_steps: ${n_action_steps}
    render_obs_key: 'agentview_image'
    fps: 10
    crf: 22
    past_action: ${past_action_visible}
    abs_action: *abs_action
    tqdm_interval_sec: 1.0
    n_envs: 32

  dataset:
    _target_: ${dataset}
    n_demo: ${n_demo}
    shape_meta: *shape_meta
    dataset_path: ${dataset_path}
    horizon: ${horizon}
    # pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
    # pad_after: ${eval:'${n_action_steps}-1'}
    n_obs_steps: ${dataset_obs_steps}
    abs_action: *abs_action
    rotation_rep: 'rotation_6d'
    use_legacy_normalizer: False
    use_cache: True
    seed: 42
    val_ratio: 0.02
    batch_size: ${dataloader.batch_size}
    num_epochs: ${training.num_epochs}

name: diff_c
_target_: realtime_diffusion_policy.workspace.robomimic.train_diffusion_unet_hybrid_workspace_rt_v4.TrainDiffusionUnetHybridWorkspace

shape_meta: ${task.shape_meta}
exp_name: "default"

task_name: stack_d1
n_demo: 100 
horizon: 32
n_obs_steps: 1
n_action_steps: 1
n_latency_steps: 0
dataset_obs_steps: ${n_obs_steps}
past_action_visible: False
obs_as_global_cond: True
dataset: realtime_diffusion_policy.dataset.robomimic.replay_image_dataset_rt_v8.RobomimicReplayImageDatasetRTV8
dataset_path: data/robomimic/datasets/${task_name}/${task_name}_abs.hdf5

policy:
  _target_: realtime_diffusion_policy.policy.robomimic.diffusion_unet_hybrid_image_policy_rt_v4.SlidingWindowDiffusionPolicy
  shape_meta: ${shape_meta}
  
  noise_scheduler:
    _target_: diffusers.schedulers.scheduling_ddim.DDIMScheduler
    num_train_timesteps: 100
    beta_start: 0.0001
    beta_end: 0.02
    beta_schedule: squaredcos_cap_v2
    clip_sample: True
    set_alpha_to_one: True
    steps_offset: 0
    prediction_type: sample

  parallel_value: 1
  window_loss_weights: exponential
  window_exp_gamma: 0.2

  horizon: ${horizon}
  n_action_steps: ${eval:'${n_action_steps}+${n_latency_steps}'}
  n_obs_steps: ${n_obs_steps}
  num_inference_steps: 20
  obs_as_global_cond: ${obs_as_global_cond}
  crop_shape: [76, 76]
  diffusion_step_embed_dim: 128
  down_dims: [256, 512, 1024]
  kernel_size: 5
  n_groups: 8
  cond_predict_scale: True
  obs_encoder_group_norm: True
  eval_fixed_crop: True
  rot_aug: False

ema:
  _target_: diffusion_policy.model.diffusion.ema_model.EMAModel
  update_after_step: 0
  inv_gamma: 1.0
  power: 0.75
  min_value: 0.0
  max_value: 0.9999

dataloader:
  batch_size: 32
  num_workers: 32
  shuffle: False # 因为训练要求的缘故，通过代码打乱episode，不打乱窗口 True False
  pin_memory: True
  persistent_workers: True  # 持久模式：50GB数据​​常驻内存

val_dataloader:
  batch_size: 32
  num_workers: 32
  shuffle: False
  pin_memory: True
  persistent_workers: True

optimizer:
  _target_: torch.optim.AdamW
  lr: 1.0e-4
  betas: [0.95, 0.999]
  eps: 1.0e-8
  weight_decay: 1.0e-6

training:
  device: "cuda:0"
  seed: 42
  debug: False
  resume: True
  lr_scheduler: cosine
  lr_warmup_steps: 500
  clip_grad_norm: 1.0
  num_epochs: 600
  gradient_accumulate_every: 1
  use_ema: True
  rollout_every: 10
  checkpoint_every: 10
  val_every: 10
  sample_every: 5
  max_train_steps: null
  max_val_steps: null
  tqdm_interval_sec: 1.0

logging:
  project: diffusion_policy_${task_name}
  resume: True
  mode: online
  name: diff_c_demo${n_demo}
  tags: ["${name}", "${task_name}", "${exp_name}"]
  id: null
  group: null

checkpoint:
  topk:
    monitor_key: test_mean_score
    mode: max
    k: 5
    format_str: 'epoch={epoch:04d}-test_mean_score={test_mean_score:.4f}.ckpt'
  save_last_ckpt: True
  save_last_snapshot: False

multi_run:
  run_dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  wandb_name_base: ${now:%Y.%m.%d-%H.%M.%S}_${name}_${task_name}

hydra:
  job:
    override_dirname: ${name}
  run:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
  sweep:
    dir: data/outputs/${now:%Y.%m.%d}/${now:%H.%M.%S}_${name}_${task_name}
    subdir: ${hydra.job.num}
